// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdatqeudzpoaczlitjma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkYXRxZXVkenBvYWN6bGl0am1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODcwMzQsImV4cCI6MjA3MDY2MzAzNH0.lXbr0WQDHAZiM7EJdL-Zu3-xQ01gx4qi-cBG8HZ9sdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});